In [1]:
import numpy as np

In [2]:
a = np.array([[1,6], [2,8], [3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

### Task 1

In [3]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Task 2

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task 3

In [5]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [6]:
a.shape[0]

5

In [7]:
cov_manually = a_centered_sp / (a.shape[0] - 1)
cov_manually

2.0

### Task 4

In [8]:
cov_np = np.cov(a.T)
cov_np

array([[1. , 2. ],
       [2. , 4.3]])

In [9]:
cov_manually == cov_np[0][1]

True